# Generated by Django 2.1.3 on 2019-03-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_count', models.IntegerField()),
                ('press', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('num_players', models.IntegerField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.IntegerField()),
                ('kp', models.BooleanField(default=False)),
                ('hcp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hcp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='golf_scorecard.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(max_length=255)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_scorecard.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50)),
                ('players', models.ManyToManyField(through='golf_scorecard.Player', to='golf_scorecard.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('game_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golf_scorecard.GameInfo')),
                ('current_hole', models.IntegerField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf_scorecard.Team'),
        ),
        migrations.AddField(
            model_name='holes',
            name='scores',
            field=models.ManyToManyField(to='golf_scorecard.Scores'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_scorecard.Team'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='games',
            field=models.ManyToManyField(blank=True, to='golf_scorecard.Game'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='holes',
            field=models.ManyToManyField(blank=True, to='golf_scorecard.Holes'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='players',
            field=models.ManyToManyField(blank=True, to='golf_scorecard.Player'),
        ),
    ]
