# Generated by Django 2.1.3 on 2019-03-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_scorecard', '0003_auto_20190324_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='players',
            field=models.ManyToManyField(to='golf_scorecard.Person'),
        ),
    ]
