# Generated by Django 2.0.7 on 2018-11-06 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('career', models.CharField(blank=True, max_length=250)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(choices=[('IB', 'IB'), ('AP', 'AP'), ('Running Start', 'Running Start'), ('Honors', 'Honors'), ('Gen Ed', 'Gen Ed')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
