# Generated by Django 2.0.7 on 2018-11-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_newsletter'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.NewsletterUser'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
