# Generated by Django 2.0.7 on 2018-11-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribed',
        ),
    ]
