# Generated by Django 2.0.7 on 2018-10-14 04:08

from django.db import migrations, models
import image_cropping.fields
import website.utils.fileutils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '245x245', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=website.utils.fileutils.UniquePathAndRename('blog/posts', True)),
        ),
    ]
