# Generated by Django 2.0.7 on 2018-11-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('blog', '0004_auto_20181013_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_gallery',
            field=models.ManyToManyField(to='website.Image'),
        ),
    ]
